### ISSUE TITLE
dekorate.component.name="" is empty

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/hal#50]
## Issue

When we use the new command `hal component create -t client fruit-client-sb`, then the `src/main/resources/application.properties` file contains an empty dekorate component name 

```
dekorate.component.name=
```

The consequence is that now, when we build the project, then the dekorate halkyon yml file contains as component name -> `myproject`
```
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "halkyon.io/v1beta1"
  kind: "Component"
  metadata:
    labels:
      app: "myproject"
    name: "myproject"
  spec:
    deploymentMode: "dev"
    runtime: "spring-boot"
    version: "2.1.6.RELEASE"
    exposeService: true
    port: 8080
```
